# -*- coding: utf-8 -*-
"""data-science-task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGmIySjjeBmnaKHRxFty9H4CBERsTq13
"""



!pip install -U kaleido
import numpy as np
import pandas as pd
import plotly.express as px
from textblob import TextBlob
import matplotlib.pyplot as plt

df = pd.read_csv('worldbank.csv')

df.head()

df.shape



df.columns



"""# Select population data from 2010 to 2018"""

years = [str(y) for y in range(2010, 2019)]
df_selected = df[["Country Name"] + years].dropna()



"""# Plot histogram for population distribution across countries over the years 2010-2018"""

plt.figure(figsize=(12, 6))
for year in years:
    plt.hist(df_selected[year], bins=30, alpha=0.5, label=year, edgecolor="black")

plt.xlabel("Population")
plt.ylabel("Number of Countries")
plt.title("Population Distribution Across Countries (2010-2018)")
plt.xscale("log")  # Log scale for better visualization
plt.legend(title="Year")
plt.grid(True, which="both", linestyle="--", linewidth=0.5)
plt.show()